package org.firstinspires.ftc.teamcode.webinterface;

import android.content.Context;

import org.firstinspires.ftc.ftccommon.external.WebHandlerRegistrar;
import org.firstinspires.ftc.robotcore.internal.webserver.WebHandler;
import com.qualcomm.robotcore.util.RobotLog; // added logging

import fi.iki.elonen.NanoHTTPD;

/**
 * Improved styling for the FTC Program and Manage web interface
 *
 * This class injects custom CSS to improve the look and feel of the built-in
 * Blocks and OnBot Java web interface.
 *
 * Access the improved styles by navigating to:
 * http://192.168.43.1:8080/improved-styles.css
 *
 * Then add this line to inject the styles into the existing interface:
 * <link rel="stylesheet" href="/improved-styles.css">
 */
public class ImprovedWebStyling {
    // Added TAG for logging
    private static final String TAG = "ImprovedWebStyling";

    /**
     * This method is automatically called by the FTC SDK to register web handlers
     */
    @WebHandlerRegistrar
    public static void registerStyleHandler(Context context, Object manager) {
        RobotLog.ii(TAG, "Attempting to register improved style handlers");
        try {
            // Use reflection to call the register method
            manager.getClass()
                .getMethod("register", String.class, WebHandler.class)
                .invoke(manager, "/improved-styles.css", new ImprovedStylesHandler());
            RobotLog.ii(TAG, "Registered /improved-styles.css endpoint");

            manager.getClass()
                .getMethod("register", String.class, WebHandler.class)
                .invoke(manager, "/custom/style-injector", new StyleInjectorPageHandler());
            RobotLog.ii(TAG, "Registered /custom/style-injector endpoint");

            // Fallback simple test endpoint to verify registration path
            manager.getClass()
                .getMethod("register", String.class, WebHandler.class)
                .invoke(manager, "/custom/teststyle", new SimpleTestHandler());
            RobotLog.ii(TAG, "Registered /custom/teststyle endpoint");
        } catch (Exception e) {
            RobotLog.ee(TAG, "Failed to register style endpoints: " + e);
            // Keep existing stack trace for deeper debugging if connected via logcat
            e.printStackTrace();
        }
    }

    /**
     * Handler that serves the improved CSS stylesheet
     */
    public static class ImprovedStylesHandler implements WebHandler { // changed to public
        @Override
        public NanoHTTPD.Response getResponse(NanoHTTPD.IHTTPSession session) {
            String css = getImprovedCSS();
            return NanoHTTPD.newFixedLengthResponse(
                NanoHTTPD.Response.Status.OK,
                "text/css",
                css
            );
        }
    }

    /**
     * Handler that provides instructions and a test page
     */
    public static class StyleInjectorPageHandler implements WebHandler { // changed to public
        @Override
        public NanoHTTPD.Response getResponse(NanoHTTPD.IHTTPSession session) {
            String html = generateInstructionsPage();
            return NanoHTTPD.newFixedLengthResponse(
                NanoHTTPD.Response.Status.OK,
                NanoHTTPD.MIME_HTML,
                html
            );
        }
    }

    /** Simple test handler to verify any endpoint works */
    public static class SimpleTestHandler implements WebHandler { // changed to public
        @Override
        public NanoHTTPD.Response getResponse(NanoHTTPD.IHTTPSession session) {
            String html = "<html><head><title>Style Test</title></head><body>" +
                    "<h1>Style Handler Loaded</h1>" +
                    "<p>If you can see this page at /custom/teststyle then the registrar worked.</p>" +
                    "<ul>" +
                    "<li><a href='/improved-styles.css'>Improved Styles CSS</a></li>" +
                    "<li><a href='/custom/style-injector'>Style Injector Page</a></li>" +
                    "</ul>" +
                    "</body></html>";
            return NanoHTTPD.newFixedLengthResponse(NanoHTTPD.Response.Status.OK, NanoHTTPD.MIME_HTML, html);
        }
    }

    /**
     * Generate improved CSS for the Program and Manage interface
     */
    private static String getImprovedCSS() {
        return "/* Improved FTC Program and Manage Interface Styles */\n" +
                "/* Automatically generated by ImprovedWebStyling.java */\n\n" +

                "/* === GLOBAL IMPROVEMENTS === */\n" +
                ":root {\n" +
                "    --primary-color: #2196F3;\n" +
                "    --primary-dark: #1976D2;\n" +
                "    --primary-light: #BBDEFB;\n" +
                "    --accent-color: #FF9800;\n" +
                "    --success-color: #4CAF50;\n" +
                "    --warning-color: #FF9800;\n" +
                "    --error-color: #F44336;\n" +
                "    --background: #FAFAFA;\n" +
                "    --card-background: #FFFFFF;\n" +
                "    --text-primary: #212121;\n" +
                "    --text-secondary: #757575;\n" +
                "    --border-color: #E0E0E0;\n" +
                "    --shadow: 0 2px 4px rgba(0,0,0,0.1);\n" +
                "    --shadow-hover: 0 4px 8px rgba(0,0,0,0.15);\n" +
                "}\n\n" +

                "/* Smooth scrolling and better font rendering */\n" +
                "html {\n" +
                "    scroll-behavior: smooth;\n" +
                "}\n\n" +

                "body {\n" +
                "    font-family: 'Roboto', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif !important;\n" +
                "    background: var(--background) !important;\n" +
                "    color: var(--text-primary) !important;\n" +
                "    line-height: 1.6 !important;\n" +
                "    -webkit-font-smoothing: antialiased !important;\n" +
                "    -moz-osx-font-smoothing: grayscale !important;\n" +
                "}\n\n" +

                "/* === BUTTONS === */\n" +
                "button, .button, input[type='button'], input[type='submit'] {\n" +
                "    background: var(--primary-color) !important;\n" +
                "    color: white !important;\n" +
                "    border: none !important;\n" +
                "    border-radius: 4px !important;\n" +
                "    padding: 10px 20px !important;\n" +
                "    font-size: 14px !important;\n" +
                "    font-weight: 500 !important;\n" +
                "    cursor: pointer !important;\n" +
                "    transition: all 0.3s ease !important;\n" +
                "    box-shadow: var(--shadow) !important;\n" +
                "    text-transform: uppercase !important;\n" +
                "    letter-spacing: 0.5px !important;\n" +
                "}\n\n" +

                "button:hover, .button:hover, input[type='button']:hover, input[type='submit']:hover {\n" +
                "    background: var(--primary-dark) !important;\n" +
                "    box-shadow: var(--shadow-hover) !important;\n" +
                "    transform: translateY(-2px) !important;\n" +
                "}\n\n" +

                "button:active, .button:active, input[type='button']:active, input[type='submit']:active {\n" +
                "    transform: translateY(0) !important;\n" +
                "    box-shadow: var(--shadow) !important;\n" +
                "}\n\n" +

                "button:disabled, .button:disabled {\n" +
                "    opacity: 0.5 !important;\n" +
                "    cursor: not-allowed !important;\n" +
                "    transform: none !important;\n" +
                "}\n\n" +

                "/* === INPUT FIELDS === */\n" +
                "input[type='text'], input[type='password'], input[type='email'], \n" +
                "input[type='number'], textarea, select {\n" +
                "    border: 1px solid var(--border-color) !important;\n" +
                "    border-radius: 4px !important;\n" +
                "    padding: 10px !important;\n" +
                "    font-size: 14px !important;\n" +
                "    transition: all 0.3s ease !important;\n" +
                "    background: white !important;\n" +
                "}\n\n" +

                "input:focus, textarea:focus, select:focus {\n" +
                "    outline: none !important;\n" +
                "    border-color: var(--primary-color) !important;\n" +
                "    box-shadow: 0 0 0 3px rgba(33, 150, 243, 0.1) !important;\n" +
                "}\n\n" +

                "/* === CARDS AND PANELS === */\n" +
                ".card, .panel, .block, [class*='card'], [class*='panel'] {\n" +
                "    background: var(--card-background) !important;\n" +
                "    border-radius: 8px !important;\n" +
                "    box-shadow: var(--shadow) !important;\n" +
                "    padding: 20px !important;\n" +
                "    margin-bottom: 20px !important;\n" +
                "    transition: all 0.3s ease !important;\n" +
                "    border: 1px solid var(--border-color) !important;\n" +
                "}\n\n" +

                ".card:hover, .panel:hover {\n" +
                "    box-shadow: var(--shadow-hover) !important;\n" +
                "}\n\n" +

                "/* === HEADERS === */\n" +
                "h1, h2, h3, h4, h5, h6 {\n" +
                "    color: var(--text-primary) !important;\n" +
                "    font-weight: 500 !important;\n" +
                "    margin-top: 0 !important;\n" +
                "}\n\n" +

                "h1 { font-size: 2.5em !important; }\n" +
                "h2 { font-size: 2em !important; }\n" +
                "h3 { font-size: 1.75em !important; }\n\n" +

                "/* === NAVIGATION / TABS === */\n" +
                "nav, .nav, .tabs, [class*='nav'], [class*='tab'] {\n" +
                "    background: var(--card-background) !important;\n" +
                "    box-shadow: var(--shadow) !important;\n" +
                "    border-radius: 4px !important;\n" +
                "}\n\n" +

                ".tab, .nav-item, [class*='tab-'] {\n" +
                "    border-radius: 4px !important;\n" +
                "    transition: all 0.3s ease !important;\n" +
                "}\n\n" +

                ".tab:hover, .nav-item:hover {\n" +
                "    background: var(--primary-light) !important;\n" +
                "}\n\n" +

                ".tab.active, .nav-item.active {\n" +
                "    background: var(--primary-color) !important;\n" +
                "    color: white !important;\n" +
                "}\n\n" +

                "/* === TABLES === */\n" +
                "table {\n" +
                "    width: 100% !important;\n" +
                "    border-collapse: collapse !important;\n" +
                "    background: var(--card-background) !important;\n" +
                "    border-radius: 8px !important;\n" +
                "    overflow: hidden !important;\n" +
                "    box-shadow: var(--shadow) !important;\n" +
                "}\n\n" +

                "th {\n" +
                "    background: var(--primary-color) !important;\n" +
                "    color: white !important;\n" +
                "    padding: 12px !important;\n" +
                "    text-align: left !important;\n" +
                "    font-weight: 500 !important;\n" +
                "}\n\n" +

                "td {\n" +
                "    padding: 12px !important;\n" +
                "    border-bottom: 1px solid var(--border-color) !important;\n" +
                "}\n\n" +

                "tr:hover {\n" +
                "    background: var(--background) !important;\n" +
                "}\n\n" +

                "tr:last-child td {\n" +
                "    border-bottom: none !important;\n" +
                "}\n\n" +

                "/* === ALERTS / NOTIFICATIONS === */\n" +
                ".alert, .notification, .message, [class*='alert'], [class*='notification'] {\n" +
                "    padding: 15px 20px !important;\n" +
                "    border-radius: 4px !important;\n" +
                "    margin-bottom: 15px !important;\n" +
                "    border-left: 4px solid !important;\n" +
                "}\n\n" +

                ".alert.success, .success {\n" +
                "    background: #E8F5E9 !important;\n" +
                "    border-left-color: var(--success-color) !important;\n" +
                "    color: #2E7D32 !important;\n" +
                "}\n\n" +

                ".alert.warning, .warning {\n" +
                "    background: #FFF3E0 !important;\n" +
                "    border-left-color: var(--warning-color) !important;\n" +
                "    color: #E65100 !important;\n" +
                "}\n\n" +

                ".alert.error, .error {\n" +
                "    background: #FFEBEE !important;\n" +
                "    border-left-color: var(--error-color) !important;\n" +
                "    color: #C62828 !important;\n" +
                "}\n\n" +

                ".alert.info, .info {\n" +
                "    background: #E3F2FD !important;\n" +
                "    border-left-color: var(--primary-color) !important;\n" +
                "    color: #1565C0 !important;\n" +
                "}\n\n" +

                "/* === CODE EDITOR IMPROVEMENTS === */\n" +
                "pre, code {\n" +
                "    font-family: 'Fira Code', 'Monaco', 'Consolas', monospace !important;\n" +
                "    background: #1E1E1E !important;\n" +
                "    color: #D4D4D4 !important;\n" +
                "    padding: 15px !important;\n" +
                "    border-radius: 4px !important;\n" +
                "    overflow-x: auto !important;\n" +
                "    line-height: 1.5 !important;\n" +
                "}\n\n" +

                "code {\n" +
                "    padding: 2px 6px !important;\n" +
                "    font-size: 0.9em !important;\n" +
                "}\n\n" +

                "/* === SCROLLBARS === */\n" +
                "::-webkit-scrollbar {\n" +
                "    width: 12px !important;\n" +
                "    height: 12px !important;\n" +
                "}\n\n" +

                "::-webkit-scrollbar-track {\n" +
                "    background: var(--background) !important;\n" +
                "}\n\n" +

                "::-webkit-scrollbar-thumb {\n" +
                "    background: #BDBDBD !important;\n" +
                "    border-radius: 6px !important;\n" +
                "}\n\n" +

                "::-webkit-scrollbar-thumb:hover {\n" +
                "    background: #9E9E9E !important;\n" +
                "}\n\n" +

                "/* === LOADING / SPINNER === */\n" +
                ".spinner, .loading, [class*='spinner'], [class*='loading'] {\n" +
                "    border: 3px solid var(--border-color) !important;\n" +
                "    border-top-color: var(--primary-color) !important;\n" +
                "    border-radius: 50% !important;\n" +
                "    animation: spin 1s linear infinite !important;\n" +
                "}\n\n" +

                "@keyframes spin {\n" +
                "    0% { transform: rotate(0deg); }\n" +
                "    100% { transform: rotate(360deg); }\n" +
                "}\n\n" +

                "/* === MODAL / DIALOG === */\n" +
                ".modal, .dialog, [class*='modal'], [class*='dialog'] {\n" +
                "    background: var(--card-background) !important;\n" +
                "    border-radius: 8px !important;\n" +
                "    box-shadow: 0 10px 40px rgba(0,0,0,0.2) !important;\n" +
                "    padding: 0 !important;\n" +
                "}\n\n" +

                ".modal-header, .dialog-header {\n" +
                "    background: var(--primary-color) !important;\n" +
                "    color: white !important;\n" +
                "    padding: 20px !important;\n" +
                "    border-radius: 8px 8px 0 0 !important;\n" +
                "}\n\n" +

                ".modal-body, .dialog-body {\n" +
                "    padding: 20px !important;\n" +
                "}\n\n" +

                ".modal-footer, .dialog-footer {\n" +
                "    padding: 20px !important;\n" +
                "    background: var(--background) !important;\n" +
                "    border-radius: 0 0 8px 8px !important;\n" +
                "    text-align: right !important;\n" +
                "}\n\n" +

                "/* === LINKS === */\n" +
                "a {\n" +
                "    color: var(--primary-color) !important;\n" +
                "    text-decoration: none !important;\n" +
                "    transition: all 0.3s ease !important;\n" +
                "}\n\n" +

                "a:hover {\n" +
                "    color: var(--primary-dark) !important;\n" +
                "    text-decoration: underline !important;\n" +
                "}\n\n" +

                "/* === BADGES / CHIPS === */\n" +
                ".badge, .chip, .tag, [class*='badge'], [class*='chip'], [class*='tag'] {\n" +
                "    display: inline-block !important;\n" +
                "    padding: 4px 12px !important;\n" +
                "    border-radius: 12px !important;\n" +
                "    font-size: 0.85em !important;\n" +
                "    font-weight: 500 !important;\n" +
                "    background: var(--primary-light) !important;\n" +
                "    color: var(--primary-dark) !important;\n" +
                "}\n\n" +

                "/* === TOOLTIPS === */\n" +
                "[title]:hover::after {\n" +
                "    content: attr(title) !important;\n" +
                "    position: absolute !important;\n" +
                "    background: #263238 !important;\n" +
                "    color: white !important;\n" +
                "    padding: 8px 12px !important;\n" +
                "    border-radius: 4px !important;\n" +
                "    font-size: 12px !important;\n" +
                "    white-space: nowrap !important;\n" +
                "    z-index: 1000 !important;\n" +
                "}\n\n" +

                "/* === RESPONSIVE IMPROVEMENTS === */\n" +
                "@media (max-width: 768px) {\n" +
                "    body {\n" +
                "        font-size: 14px !important;\n" +
                "    }\n" +
                "    \n" +
                "    .card, .panel {\n" +
                "        padding: 15px !important;\n" +
                "    }\n" +
                "    \n" +
                "    button, .button {\n" +
                "        padding: 8px 16px !important;\n" +
                "        font-size: 12px !important;\n" +
                "    }\n" +
                "}\n\n" +

                "/* === ACCESSIBILITY === */\n" +
                "*:focus {\n" +
                "    outline: 2px solid var(--primary-color) !important;\n" +
                "    outline-offset: 2px !important;\n" +
                "}\n\n" +

                "/* High contrast mode support */\n" +
                "@media (prefers-contrast: high) {\n" +
                "    :root {\n" +
                "        --border-color: #000000 !important;\n" +
                "        --text-primary: #000000 !important;\n" +
                "    }\n" +
                "}\n\n" +

                "/* Reduce motion for accessibility */\n" +
                "@media (prefers-reduced-motion: reduce) {\n" +
                "    *, *::before, *::after {\n" +
                "        animation-duration: 0.01ms !important;\n" +
                "        animation-iteration-count: 1 !important;\n" +
                "        transition-duration: 0.01ms !important;\n" +
                "    }\n" +
                "}\n\n" +

                "/* === PRINT STYLES === */\n" +
                "@media print {\n" +
                "    body {\n" +
                "        background: white !important;\n" +
                "    }\n" +
                "    \n" +
                "    .card, .panel {\n" +
                "        box-shadow: none !important;\n" +
                "        border: 1px solid #000 !important;\n" +
                "    }\n" +
                "    \n" +
                "    button, .button {\n" +
                "        display: none !important;\n" +
                "    }\n" +
                "}\n";
    }

    /**
     * Generate instructions page
     */
    private static String generateInstructionsPage() {
        return "<!DOCTYPE html>\n" +
                "<html>\n" +
                "<head>\n" +
                "    <meta charset='UTF-8'>\n" +
                "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n" +
                "    <title>Improved Web Styling - Instructions</title>\n" +
                "    <link rel='stylesheet' href='/improved-styles.css'>\n" +
                "</head>\n" +
                "<body style='padding: 40px; max-width: 1200px; margin: 0 auto;'>\n" +
                "    <h1>✨ Improved FTC Web Interface Styling</h1>\n" +
                "    \n" +
                "    <div class='card'>\n" +
                "        <h2>Installation Instructions</h2>\n" +
                "        <p>The improved CSS is now available at: <code>/improved-styles.css</code></p>\n" +
                "        \n" +
                "        <h3>Option 1: Browser Extension (Recommended)</h3>\n" +
                "        <ol>\n" +
                "            <li>Install a browser extension like <strong>Stylus</strong> (Chrome/Firefox)</li>\n" +
                "            <li>Create a new style for <code>192.168.43.1:8080</code></li>\n" +
                "            <li>Copy the CSS from <a href='/improved-styles.css' target='_blank'>/improved-styles.css</a></li>\n" +
                "            <li>Save and enjoy the improved interface!</li>\n" +
                "        </ol>\n" +
                "        \n" +
                "        <h3>Option 2: Browser DevTools</h3>\n" +
                "        <ol>\n" +
                "            <li>Open your browser's DevTools (F12)</li>\n" +
                "            <li>Go to the Console tab</li>\n" +
                "            <li>Paste this code and press Enter:</li>\n" +
                "        </ol>\n" +
                "        <pre><code>var link = document.createElement('link');\n" +
                "link.rel = 'stylesheet';\n" +
                "link.href = '/improved-styles.css';\n" +
                "document.head.appendChild(link);</code></pre>\n" +
                "        \n" +
                "        <h3>Option 3: Bookmark Injection</h3>\n" +
                "        <ol>\n" +
                "            <li>Create a new bookmark</li>\n" +
                "            <li>Name it: <strong>Load Improved Styles</strong></li>\n" +
                "            <li>Set URL to:</li>\n" +
                "        </ol>\n" +
                "        <pre><code>javascript:(function(){var l=document.createElement('link');l.rel='stylesheet';l.href='/improved-styles.css';document.head.appendChild(l);})();</code></pre>\n" +
                "        <p>Click the bookmark on any Program and Manage page to load the improved styles!</p>\n" +
                "    </div>\n" +
                "    \n" +
                "    <div class='card'>\n" +
                "        <h2>Style Preview</h2>\n" +
                "        \n                " +
                "        <h3>Buttons</h3>\n" +
                "        <button>Primary Button</button>\n" +
                "        <button disabled>Disabled Button</button>\n" +
                "        \n" +
                "        <h3>Inputs</h3>\n" +
                "        <input type='text' placeholder='Text input' style='width: 300px;'><br><br>\n" +
                "        <select style='width: 300px;'>\n" +
                "            <option>Option 1</option>\n" +
                "            <option>Option 2</option>\n" +
                "        </select>\n" +
                "        \n" +
                "        <h3>Alerts</h3>\n" +
                "        <div class='alert success'>Success message</div>\n" +
                "        <div class='alert warning'>Warning message</div>\n" +
                "        <div class='alert error'>Error message</div>\n" +
                "        <div class='alert info'>Info message</div>\n" +
                "        \n" +
                "        <h3>Table</h3>\n" +
                "        <table>\n" +
                "            <thead>\n" +
                "                <tr><th>Name</th><th>Value</th><th>Status</th></tr>\n" +
                "            </thead>\n" +
                "            <tbody>\n" +
                "                <tr><td>Motor 1</td><td>0.75</td><td><span class='badge'>Running</span></td></tr>\n" +
                "                <tr><td>Motor 2</td><td>0.50</td><td><span class='badge'>Running</span></td></tr>\n" +
                "                <tr><td>Servo 1</td><td>0.25</td><td><span class='badge'>Stopped</span></td></tr>\n" +
                "            </tbody>\n" +
                "        </table>\n" +
                "    </div>\n" +
                "    \n" +
                "    <div class='card'>\n" +
                "        <h2>Features</h2>\n" +
                "        <ul>\n" +
                "            <li>✅ Modern, clean Material Design-inspired interface</li>\n" +
                "            <li>✅ Improved button styles with hover effects</li>\n" +
                "            <li>✅ Better form controls and input fields</li>\n" +
                "            <li>✅ Enhanced card and panel layouts</li>\n" +
                "            <li>✅ Styled tables with hover effects</li>\n" +
                "            <li>✅ Custom scrollbars</li>\n" +
                "            <li>✅ Responsive design improvements</li>\n" +
                "            <li>✅ Accessibility enhancements</li>\n" +
                "            <li>✅ Dark mode code blocks</li>\n" +
                "            <li>✅ Smooth animations and transitions</li>\n" +
                "        </ul>\n" +
                "    </div>\n" +
                "    \n" +
                "    <div class='card'>\n" +
                "        <h2>Navigation</h2>\n" +
                "        <p>\n" +
                "            <a href='/'>Robot Controller Home</a> | \n" +
                "            <a href='/improved-styles.css'>View Raw CSS</a> | \n" +
                "            <a href='/java/editor.html'>OnBot Java</a> | \n" +
                "            <a href='/blocks/index.html'>Blocks</a>\n" +
                "        </p>\n" +
                "    </div>\n" +
                "</body>\n" +
                "</html>";
    }
}

